# Generated by Django 3.2.25 on 2024-04-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_cost',
            new_name='shipping_cost',
        ),
    ]
