# Generated by Django 3.2.25 on 2024-06-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_rename_line_item_total_orderlineitem_lineitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='lineitem_total',
            new_name='line_item_total',
        ),
    ]
